# This file forces cargo commands run in the repository to follow the rust version contained here.
# This is particulary useful to maintain consistency between workflow and local runs
[toolchain]
channel = "1.88.0"